LAB5/Controllers/BrandController.cs
using System.Threading.Tasks;
using LAB5.Services;
using Microsoft.AspNetCore.Mvc;

namespace LAB5.Controllers
{
    public class BrandController : Controller
    {
        private readonly BrandService _brandService;

        public BrandController(BrandService brandService)
        {
            _brandService = brandService;
        }

        public async Task<IActionResult> Index()
        {
            var brands = await _brandService.GetBrandsAsync();
            return View(brands);
        }

        public async Task<IActionResult> Details(int id)
        {
            var brand = await _brandService.GetBrandByIdAsync(id);
            if (brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }
    }
}

LAB5/Controllers/LabController.cs
using LAB5.Models;
using Microsoft.AspNetCore.Mvc;


namespace LAB5.Controllers
{
    public class LabController : Controller
    {
        private readonly IWebHostEnvironment _environment;

        public LabController(IWebHostEnvironment environment)
        {
            _environment = environment;
        }

        public IActionResult Lab1()
        {
            var model = new LabViewModel
            {
                TaskNumber = "1",
                TaskVariant = "64",
                TaskDescription = "Дано рядок, що складається із N символів.\r\nПотрібно вивести всі перестановки символів цього рядка.\r\n",
                InputDescription = "Вхідний файл INPUT.TXT містить рядок, що складається з N символів (1 ≤ N ≤ 8), символи – літери англійського алфавіту та цифри.",
                OutputDescription = "У вихідний файл OUTPUT.TXT виведіть у кожному рядку за однією перестановкою.\r\nПерестановки можна виводити у будь-якому порядку.\r\nПовторень і рядків, які є перестановками вихідної, не повинно бути.",
                TestCases = new List<TestCase>
            {
                new TestCase { Input = "AB", Output = "AB\nBA" },
                new TestCase { Input = "122", Output = "122\n212\n221" }
            }
            };
            return View(model);
        }

        public IActionResult Lab2()
        {
            var model = new LabViewModel
            {
                TaskNumber = "2",
                TaskVariant = "64",
                TaskDescription = "Автомобільні пробки трапляються скрізь, навіть у нашому маленькому місті.\r\nДороги у нас мають по дві смуги в одному напрямку, а автомобілі лише двох видів:\r\nлегкові (у пробці займають квадратне місце 1×1 від ширини однієї смуги)\r\nта вантажні (займають прямокутне місце 1×2).\r\nАвтомобілісти дуже дисципліновані: не стають упоперек смуги, не займають чужої площі, але й не залишають вільних місць.\r\nПотрібно написати програму, яка визначить кількість різних автомобільних заторів довжини N.\r\n",
                InputDescription = "Вхідний файл INPUT.TXT містить одне натуральне число N (N ≤ 1000).\r\n",
                OutputDescription = "Вихідний файл OUTPUT.TXT повинен мати знайдену кількість автомобільних пробок.",
                TestCases = new List<TestCase>
            {
                new TestCase { Input = "2", Output = "4" },
                new TestCase { Input = "3", Output = "9" }
            }
            };
            return View(model);
        }

        public IActionResult Lab3()
        {
            var model = new LabViewModel
            {
                TaskNumber = "3",
                TaskVariant = "64",
                TaskDescription = "У парку флори та фауни затіяли масштабну перебудову.\r\nОрганізатори запланували розширення площі парку, збільшення кількості екзотичних тварин та будівництво нових вольєрів.\r\nПісля затвердження плану будівельники та зоологи взялися до роботи.\r\nЗоологи зі своїм завданням впоралися: привезли нових жирафів, довгоочікуваних слонів, ігуан з карибських островів та багатьох інших тварин та птахів.\r\nА ось будівельники не встигли добудувати нові вольєри, тож привезених тварин було вирішено тимчасово розмістити у клітках.\r\nОднак і це завдання виявилося непростим, оскільки клітин може не вистачити для привезених тварин.\r\nА в одну клітинку можна помістити лише сумісних тварин.\r\nЗоологи склали таблицю сумісності тварин, представивши її як матриці A={aij} розміром N×N.\r\nЯкщо тварини з номерами i і j сумісні, то aij = 0, і якщо - ні, то aij = 1.\r\nНеобхідно визначити мінімальну кількість клітин для безпечного розміщення тварин, коли у всіх клітинах знаходяться лише сумісні між собою тварини.\r\nПри цьому в клітині може бути одна, дві і більше тварин.\r\n",
                InputDescription = "Перший рядок вхідного файлу INPUT.TXT містить число N - кількість тварин (1 ≤ N ≤ 18).\r\nДалі йде N рядків по N чисел у кожному – матриця сумісності тварин.\r\n",
                OutputDescription = "У вихідний файл OUTPUT.TXT виведіть одне ціле число – мінімальна кількість клітин, яка потрібна для безпечного розміщення тварин.",
                TestCases = new List<TestCase>
            {
                new TestCase
                {
                    Input = "5\r\n0 1 1 1 1\r\n1 0 1 1 1 \r\n1 1 0 1 1\r\n1 1 1 0 1\r\n1 1 1 1 0",
                    Output = "5"
                },
                new TestCase 
                { Input = "1\r\n0", Output = "1" }
            }
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ProcessLab(int labNumber, IFormFile inputFile)
        {
            if (inputFile == null || inputFile.Length == 0)
                return BadRequest("Please upload a file");

            // Read file contents into a string array
            string[] lines;
            using (var reader = new StreamReader(inputFile.OpenReadStream()))
            {
                var fileContent = await reader.ReadToEndAsync();
                lines = fileContent.Split(Environment.NewLine); // Split into lines
            }

            // Variable to store the processed result
            string output = null;

            // Execute the lab processing method based on lab number
            switch (labNumber)
            {
                case 1:
                    LAB1.Program.ValidateInput(lines);                    
                    output = LAB1.Program.SolveProblem(lines[0]);                    
                    break;
                case 2:
                    LAB2.Program.ValidateInput(lines);
                    string line = lines[0].Trim();                    
                    int result2 = LAB2.Program.SolveProblem(line);
                    output = result2.ToString();
                    break;
                case 3:
                    LAB3.Program.ValidateInput(lines);
                    var (N, compatibilityMatrix) = LAB3.Program.ParseInput(lines);
                    int result3 = LAB3.Program.SolveProblem(N, compatibilityMatrix);
                    output = result3.ToString();
                    break;
                default:
                    return BadRequest("Invalid lab number");
            }

            // Return result as JSON
            var result = new { output = output };
            return Json(result);
        }

    }
}

LAB5/Controllers/ProductController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LAB5.Services;

namespace LAB5.Controllers
{
    public class ProductController : Controller
    {
        private readonly ProductService _productService;

        public ProductController(ProductService productService)
        {
            _productService = productService;
        }

        public async Task<IActionResult> Index(int? brandId, string? productTypeCode, string? search, int? pageNumber, int? pageSize)
        {
            var products = await _productService.GetProductsAsync(brandId, productTypeCode, search, pageNumber, pageSize);
            return View(products);
        }

        public async Task<IActionResult> Details(int id)
        {
            var product = await _productService.GetProductByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }
    }
}

LAB5/Controllers/RetailerController.cs
using LAB5.Models;
using LAB5.Services;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace LAB5.Controllers
{
    public class RetailerController : Controller
    {
        private readonly RetailerService _retailerService;

        public RetailerController(RetailerService retailerService)
        {
            _retailerService = retailerService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var retailers = await _retailerService.GetRetailersAsync();
                return View(retailers);
            }
            catch
            {
                return View("Error");
            }
        }

        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var retailer = await _retailerService.GetRetailerByIdAsync(id);
                if (retailer == null)
                {
                    return NotFound();
                }
                return View(retailer);
            }
            catch
            {
                return View("Error");
            }
        }
    }
}

LAB5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LAB5</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css" asp-append-version="true" />    
    <link rel="stylesheet" href="~/LAB5.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />   
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LAB5</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {                           
                            <a class="nav-link text-dark" asp-controller="Lab" asp-action="Lab1">Lab #1</a>
                            <a class="nav-link text-dark" asp-controller="Lab" asp-action="Lab2">Lab #2</a>
                            <a class="nav-link text-dark" asp-controller="Lab" asp-action="Lab3">Lab #3</a>
                            <a class="nav-link text-dark" asp-controller="Product" asp-action="Index">Products</a>
                            <a class="nav-link text-dark" asp-controller="Brand" asp-action="Index">Brands</a>
                            <a class="nav-link" asp-controller="Retailer" asp-action="Index">Retailers</a>
                        }
                    </ul>

                    <!-- Профіль -->
                    @if (User.Identity.IsAuthenticated)
                    {
                        <div class="dropdown">
                            <a class="nav-link text-dark dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-user-circle-o fa-3x" aria-hidden="true"></i>
                            </a>

                            <div class="dropdown-menu dropdown-menu-end custom-dropdown" aria-labelledby="dropdownMenuLink">
                                <p class='dropdown-header'>Передивитися профіль або Вийти</p>
                                <div class='d-flex flex-column align-items-center'>
                                    <a asp-controller="Home" asp-action="Profile" class='btn btn-primary w-100 my-1'>Profile</a>
                                    <a asp-controller="Account" asp-action="Logout" class='btn btn-secondary w-100 my-1'>Logout</a>
                                </div>
                            </div>
                        </div>
                    }
                    else
                    {
                        <div class="dropdown">
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">
                                        <i class="fa fa-sign-in" aria-hidden="true"></i> Login
                                    </a>
                                </li>
                            </ul>
                        </div>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - LAB5 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>